### ISSUE TITLE
Imported journal title data has a mixture of sentence case and title case

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-journal-loader#2]
The journal data imported into fcrepo is a mixture of title case and sentence case. It would be nice if the journal titles could be converted to title case.  For example, there is ""Journal of anesthesia" and "Journal of Transplantation".  The logic should preserve titles containing acronyms e.g. "AMIA Annual Symposium Proceedings"

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
